### ISSUE TITLE
Node 16 deprecation warnings

### ISSUE THREAD

**Issue by mku514k** [ethanis/nitpicker#55]
Hello,
We are running nitpicker gha v1.6 and getting deprecation warnings as in attached picture.
![image](https://github.com/ethanis/nitpicker/assets/96818779/4257ef45-ba43-4376-927d-e4cff2420d65)

Are there any plans for updating to newer node version to get rid of those warnings?

**Comment by ethanis** [comment]
@mku514k I just created [v1.7](https://github.com/ethanis/nitpicker/releases/tag/v1.7). Can you try updating your workflow and verifying the warnings are removed?

**Comment by mku514k** [comment]
Sure, I'll test it and follow up, thanks!

**Comment by mku514k** [comment]
We updated workflow to use nitpicker v1.7 and the warnings are gone! Thanks!

**Comment by ethanis** [comment]
Great! I marked v1.7 as the latest release now. Thanks for checking in on this!
